import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { syne, poppins, openSans } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Camelweb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${syne.variable} ${poppins.variable} ${openSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
